services:
  - type: web
    name: bus-ecommerce-backend
    runtime: node
    rootDir: backend
    buildCommand: NODE_ENV=production npm install && NODE_ENV=production npm run build && cp -r src/config dist/
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        fromDatabase:
          name: bus-ecommerce-db
          property: connectionString
      - key: NODE_ENV
        value: production
    healthCheckPath: /healthcheck
    autoDeploy: true

databases:
  - name: bus-ecommerce-db
    type: mongodb
    plan: free 